CREATE DATABASE BuildWeekTeam4

USE BuildWeekTeam4

CREATE TABLE Regioni(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Nome NVARCHAR(150),
Codice NVARCHAR(50)NOT NULL)

CREATE TABLE Province(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Nome NVARCHAR(150),
Codice NVARCHAR(50)NOT NULL,
IdRegione INT NOT NULL,
FOREIGN KEY (IdRegione ) REFERENCES Regioni (Id) ON DELETE CASCADE)

CREATE TABLE Comuni(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Nome NVARCHAR(150),
Codice NVARCHAR(50)NOT NULL,
CAP NVARCHAR(50)NOT NULL,
IdProvincia INT NOT NULL,
FOREIGN KEY (IdProvincia) REFERENCES Province (Id) ON DELETE CASCADE)

CREATE TABLE TipiCambi(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Nome NVARCHAR(150),
Codice NVARCHAR(50))

CREATE TABLE Colori(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Nome NVARCHAR(150),
Codice NVARCHAR(50))

CREATE TABLE Cilindrate(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Nome NVARCHAR(150),
Codice NVARCHAR(50))

CREATE TABLE Modelli (
Id INT IDENTITY NOT NULL PRIMARY KEY,
Nome NVARCHAR(150),
Codice NVARCHAR(50)NOT NULL,
Marche NVARCHAR(50)NOT NULL,
Colore NVARCHAR(150),
Cilindrata INT NOT NULL,
DataCreazione DATETIME NOT NULL DEFAULT GETDATE())

CREATE TABLE Concessionarie(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Nome NVARCHAR(150),
Codice NVARCHAR(50))

CREATE TABLE AnagraficaClienti(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Nome NVARCHAR(150),
Cognome NVARCHAR(150),
Indirizzo NVARCHAR(250),
Telefono NVARCHAR(150),
IdComune INT NOT NULL,
FOREIGN KEY (IdComune) REFERENCES Comuni (Id) ON DELETE CASCADE)

CREATE TABLE Macchine (
Id INT IDENTITY NOT NULL PRIMARY KEY,
Targa NVARCHAR(150) NOT NULL,
NumeroSerie NVARCHAR(50)NOT NULL,
PrezzoListino DECIMAL(10, 2),
AnnoImmatricolazione DATETIME NOT NULL,
IdConcessionaria INT NOT NULL,
IdModello INT NOT NULL,
IdTipoCambio INT NOT NULL,
IdColore INT NOT NULL,
FOREIGN KEY (IdConcessionaria) REFERENCES Concessionarie (Id) ON DELETE CASCADE,
FOREIGN KEY (IdModello) REFERENCES Modelli (Id) ON DELETE CASCADE,
FOREIGN KEY (IdTipoCambio) REFERENCES TipiCambi (Id) ON DELETE CASCADE,
FOREIGN KEY (IdColore) REFERENCES Colori (Id) ON DELETE CASCADE)

CREATE TABLE Vendite (
Id INT IDENTITY NOT NULL PRIMARY KEY,
PrezzoVendita DECIMAL(10, 2),
DataVendita DATETIME NOT NULL DEFAULT GETDATE(),
IdCliente INT NOT NULL,
IdMacchina INT NOT NULL,
IdConcessionaria INT NOT NULL,
FOREIGN KEY (IdCliente) REFERENCES AnagraficaClienti (Id) ON DELETE CASCADE,
FOREIGN KEY (IdMacchina) REFERENCES Macchine (Id) ON DELETE CASCADE,
FOREIGN KEY (IdConcessionaria) REFERENCES Concessionarie (Id) ON DELETE CASCADE)
